FROM ghcr.io/linuxserver/baseimage-kasmvnc:alpine319
RUN apk --no-cache add supervisor opencv mpv mpv-libs ffmpeg jq libheif wget zstd\
 openssl nodejs font-noto font-noto-emoji font-noto-cjk \
 py3-pyside6 py3-beautifulsoup4 py3-pillow py3-numpy py3-openssl py3-cryptography py3-pip py3-opencv py3-lxml py3-chardet \
 py3-psutil py3-pysocks py3-requests py3-twisted py3-yaml py3-lz4 py3-html5lib py3-dateutil py3-qtpy py3-mpv py3-service_identity
RUN apk --no-cache add build-base python3-dev fribidi-dev harfbuzz-dev jpeg-dev lcms2-dev openjpeg-dev libjpeg-turbo-dev libheif-dev
RUN pip install --break-system-packages Send2Trash cloudscraper pyparsing cbor2 Pympler pillow-heif dateparser
RUN mkdir /opt/hydrus && \
    wget -O /opt/hydrus/hydrus.tar.zst https://github.com/hydrusnetwork/hydrus/archive/refs/tags/v563.tar.gz && \
    cd /opt/hydrus && \
    tar -xvf 'hydrus.tar.zst' && \
    mv hydrus-*/* /opt/hydrus/ && \
    rm -r hydrus-* && \
    rm 'hydrus.tar.zst' && \ 
    chmod -R 777 /opt/hydrus
COPY root /
COPY supervisord.conf /etc/supervisord.conf

ENV HYDRUS_DB="/opt/hydrus/db" \
    HYDRUS_TEMP="/tmp" \
    NO_FULL="TRUE" \
    TITLE="Hydrus Client"
